### ISSUE TITLE
Assignment 3a: RBF

### ISSUE THREAD

**Issue by yentyu** [CU-Denver-UQ/Math1376#15]
This problem should probably be split into more parts, even with a video explanation.

My recommendation is to give the introduction and then have a few questions _just on metrics_ so they have some basic practice looking at the distances between things. I've had 3rd year math graduates in my groups who don't understand norms at all.

Similarly, I feel that it is difficult to parse what the inputs of the function that you are requesting ought to be able to pass without breaking it into manageable steps. This is an important skill for students to learn, but I can imagine them needing help with this.

One recommendation might be to give students one simple set of **test input** that they can try putting into their function.

**Comment by eecsu** [comment]
I just noticed I haven't included a figure I made for this, but I did edit this problem a lot. Look at this assignment and check out how I separate the whole thing involving norms into its own part that is not a problem. It just lets them play with it. Then I fill in more of the problem 2(b) for them with comment prompts about what they need to do in the code. It is not very onerous now. Problem 2(c) is ready to just execute once they do problem 2(b). There is reading for them to do for sure, but the level of technical difficulty in what they need to actually do is now quite low.

**Comment by yentyu** [comment]
I think this is way more manageable and a challenging but GOOD kind of challenge!

Two suggestions:

1. For the norm preamble, I'd put a hint / reminder that if they are a little confused by what the norm is doing they should print the two arrays side-by-side. This is a thing they should always be doing, but I think that this is a good place to put a reminder that this is something they can (and should) do

2. For part 2(c): I think it might be interesting to give them the answers to what the result OUGHT to be for at least one of the problems. I know the next assignment (3c) is specifically about unit tests, but I think this is a good point to start emphasizing the idea of using something we know the answer for and comparing it to what we code. And also that it is not enough for the code to just run (which I imagine will be a moment of triumph for them)!

Otherwise, I think this is an excellent re-work!

**Comment by yentyu** [comment]
Also, are you still planning on making a video for this eventually? I think a video would definitely help.
