### ISSUE TITLE
Lecture 4a: Why care about roots?

### ISSUE THREAD

**Issue by yentyu** [CU-Denver-UQ/Math1376#17]
The extra comments in reference to derivatives seems out of place since none of the examples in this section describe this phenomena, but you spend a whole paragraph talking about it.

Maybe just say something like, "Root-problems naturally arise in the context of optimization..." describe an optimization example (not in detail). Maybe mention the way that this is solved is by finding derivatives, a concept from calculus.

Is there a reason you wanted to address smoothness in addition to just noting that it arises naturally from optimization?

**Comment by eecsu** [comment]
I am going to put this content in the assignment. I just haven't created the assignment yet, so some of this is just sitting here for now.
