### ISSUE TITLE
Lecture 01-Jupyter

### ISSUE THREAD

**Issue by yentyu** [CU-Denver-UQ/Math1376#26]
Did you decide to go with the TechsmithRelay quizzing after all? Or is this just a hold over from a previous version?

**Comment by eecsu** [comment]
I was going back and forth on it up until a couple weeks ago. I just plan on having Canvas quizzes now. This should be removed if it is still there.

**Comment by eecsu** [comment]
I actually cannot find any mention of Techsmith in this notebook. Did you fetch the most recent updates to the repo? Or, is this in another file? I just can't find it.

**Comment by yentyu** [comment]
I couldn't find this either... Maybe I had an old version!

Wasn't in the most recent pull.
