### ISSUE TITLE
A personal introduction--Lecture -1?

### ISSUE THREAD

**Issue by yentyu** [CU-Denver-UQ/Math1376#27]
It occurred to me while watching the first video that it would be really helpful to have an introduction video which is an introduction video to who you are (separate from the "how do I get started" video you sent me earlier). I feel like this will be very important so that students feel like you are approachable in office hours and also so they can get a feel for your sense of humor, personality, and that you are a human (not a robot in the ether).

**Things I'd Include in this Video**

* Your face.
* Ice-breaker-y type things about yourself.
* Your teaching philosophy
* Why you are excited to teach this specific course
* What you hope students get out of the course

**Things I would not Include in this Video**

* The syllabus
* Anything about course logistics

I am not sure where the best place to put this video, but I definitely think it is important for them to see before they dive into Lecture a.

**Comment by eecsu** [comment]
I was thinking of something like this. I did send an email to students with some of this stuff early on in the summer, but I do want to make a video like this. Thanks for reminding me. I will probably do it this next week or so.
